language: go

go:
  - "1.9.x"
  - "1.10.x"
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test ./...
  - go test -c -covermode=count 
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.cov